data:
  path: data/bc_dataset_ver11.parquet

training:
  epochs: 30
  batch_size: 128
  lr: 0.0001
  pos_weight: 1
  n_folds: 5
model:
  hidden_layers: [64, 32, 16]
  activations: ["relu", "relu", "relu"]
