method: bayes
program: scripts/sweep.py
run_cap: 50
metric:
  name: val_f1
  goal: maximize

parameters:
  lr:
    values: [0.0001]
  batch_size:
    values: [64, 128]
  pos_weight:
    max: 15
    min: 5
    distribution: int_uniform
  
  hidden_layers:
    values:
      - [64, 32, 16]
      - [128, 64, 32]

  activations:
    values:
      - ["tanh", "tanh", "tanh"]
      - ["tanh", "relu", "tanh"]
