method: bayes
program: scripts/sweep.py
run_cap: 50
metric:
  name: val_f1
  goal: maximize

parameters:
  lr:
    values: [0.0001]
  batch_size:
    values: [64]
  pos_weight:
    max: 15
    min: 3
    distribution: int_uniform
  
  hidden_layers:
    values:
      - [64, 32, 16]
  activations:
    values:

      - ["tanh", "relu", "tanh"]
