method: bayes
program: scripts/sweep.py
run_cap: 50
metric:
  name: val_f1
  goal: maximize

parameters:
  lr:
    values: [0.0001, 0.00001, 0.0005]
  batch_size:
    values: [64, 128]

  hidden_layers:
    values:
      - [64, 32, 16]
      - [128, 64, 32]
  activations:
    values:
      - ["tanh", "tanh", "tanh"]
      - ["tanh", "relu", "tanh"]
      - ["relu", "relu", "relu"]
      - ["relu", "tanh", "relu"]
  pos_weight:
    min: 1
    max: 70

